--[[-------------------------------------------------------------------------
Door groups
-----------------------------------------------------------------------------
The server owner can set certain doors as owned by a group of people, identified by their jobs.


HOW TO MAKE A DOOR GROUP:
AddDoorGroup("NAME OF THE GROUP HERE, you will see this when looking at a door", Team1, Team2, team3, team4, etc.)
---------------------------------------------------------------------------]]

-- Copyright © LiveYourGame, 2021

AddDoorGroup("Gouvernement", TEAM_MAYOR, TEAM_SECRETAIRE, TEAM_GARDE, TEAM_GENDARME, TEAM_AGN, TEAM_MGN, TEAM_BRI, TEAM_SDR, TEAM_OFFICIER, TEAM_RECRUEGIGN, TEAM_MEDICGIGN, TEAM_SOLDATGIGN, TEAM_INGEGIGN, TEAM_SNIPERGIGN, TEAM_INGEGIGN, TEAM_OSUGIGN, TEAM_MARECHAL, TEAM_GENGEN, TEAM_GIGNGENERAL, TEAM_STAFF)
AddDoorGroup("Gendarmerie", TEAM_GENDARME, TEAM_AGN, TEAM_MGN, TEAM_BRI, TEAM_SDR, TEAM_OFFICIER, TEAM_RECRUEGIGN, TEAM_MEDICGIGN, TEAM_SOLDATGIGN, TEAM_INGEGIGN, TEAM_SNIPERGIGN, TEAM_INGEGIGN, TEAM_OSUGIGN, TEAM_MARECHAL, TEAM_GENGEN, TEAM_GIGNGENERAL, TEAM_STAFF)
AddDoorGroup("GIGN", TEAM_RECRUEGIGN, TEAM_MEDICGIGN, TEAM_SOLDATGIGN, TEAM_INGEGIGN, TEAM_SNIPERGIGN, TEAM_OSUGIGN, TEAM_GIGNGENERAL, TEAM_MARECHAL, TEAM_STAFF)
AddDoorGroup("État-Major", TEAM_OFFICIER, TEAM_GENGEN, TEAM_MARECHAL, TEAM_GIGNGENERAL, TEAM_STAFF)
AddDoorGroup("Banque", TEAM_PBANQUIER, TEAM_BANQUIER, TEAM_STAFF)
AddDoorGroup("Restaurant", TEAM_COOK, TEAM_STAFF)
AddDoorGroup("Gangster", TEAM_CGANGSTER, TEAM_GANGSTER, TEAM_GANGSTERV, TEAM_STAFF)
AddDoorGroup("Mafieux", TEAM_CMAFIA, TEAM_MAFIA, TEAM_MAFIAV, TEAM_STAFF)
AddDoorGroup("Yakuza", TEAM_CYAKUZA, TEAM_YAKUZA, TEAM_YAKUZAV, TEAM_STAFF)
AddDoorGroup("Braqueur", TEAM_CBRAQUEUR, TEAM_BRAQUEUR, TEAM_BRAQUEURV, TEAM_STAFF)
AddDoorGroup("Cartel", TEAM_CCARTEL, TEAM_CARTEL, TEAM_CARTELV, TEAM_STAFF)
AddDoorGroup("Crips", TEAM_CCRIPS, TEAM_CRIPS, TEAM_CRIPSV, TEAM_STAFF)
AddDoorGroup("Bloods", TEAM_CBLOODS, TEAM_BLOODS, TEAM_BLOODSV, TEAM_STAFF)
AddDoorGroup("Hôpital", TEAM_SAMU, TEAM_STAFF)
